version: "3" 
services:

    redis:
     image: redis:alpine
     container_name: redis

    webserver:
      image: nginx:alpine
      container_name: challenge-webserver
      working_dir: /application
      volumes:
        - ./src:/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "3333:80"

    php-fpm:
      build: php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php-fpm-ini-overrides.ini:/etc/php-fpm/7.1/fpm/conf.d/99-overrides.ini

    mysql:
      container_name: mysql
      image: mysql:5.7.22
      ports:
        - "3306:3306"
      command:  --max_allowed_packet=32505856
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
        - .:/application
